# 1. Obtener los valores inyectados en el controlador
GET http://localhost:8080/api/var/tagvalues

###

POST http://localhost:8080/api/var
Content-Type: application/json

{
  "name": "pinguino",
  "lastname": "tux",
  "email": "pinguino@tux.com"
}

###